### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by farnaf** [pvijay03/cse15L_Lab_Reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - incorrect expected output
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
nice work 😃 
Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by pvijay03** [comment]
What is my incorrect expected output? I had the 3 valid links: https://www.twitter.com, https://ucsd-cse15l-w22.github.io/, https://cse.ucsd.edu/.
<img width="307" alt="Screen Shot 2022-03-06 at 11 12 39 PM" src="https://user-images.githubusercontent.com/97484172/156984810-4af2fcec-e5a1-4884-8412-af62f1eec0d3.png">

**Comment by farnaf** [comment]
Hi there! We can consider a link valid when the URL that's used with a specific syntax/structure (e.g., `[]()`) turns into a markdown link. For example:

- `[hello](https://www.youtube.com/)` looks like this:  [hello](https://www.youtube.com/) 
  - we consider it valid because it turns into a link + we no longer see the URL
- `[hello] https://www.youtube.com/` looks like this:  [hello] https://www.youtube.com/ 
  - we don't consider it valid because GitHub highlights the URL as blue but doesn't turn anything into a markdown link

**Comment by pvijay03** [comment]
Do you want me to just change the screenshots with the expected output, or should I change those screenshots, the screenshots of the tests running, and the code change I would do?

**Comment by farnaf** [comment]
Changing the expected output screenshot(s) is enough!
